### PR TITLE
Add windows cell usage instructions

### PR DESCRIPTION
**Pull request by sneal**
Obviously this isn't supported, but there's enough interest out there to at least document the steps required in order to get a working Windows Cell with PCF Dev.

### CODE REVIEW

**Comment by sclevine** [comment]
Let's wait to merge this until we make the necessary PCF Dev changes to fix the boot process to allow all the services to start. (Killing the boot script early prevents important setup code from running.)

**Comment by abbyachau** [comment]
Hi @sclevine, sure thanks. Just let us know when you are ready for us to do so.

Thanks!

Abby

**Comment by bentarnoff** [comment]
Hey @sclevine it's been awhile since this PR, so we wanted to check in.

**Comment by bentarnoff** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
